// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvyzjgzabcilnxswbqew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2eXpqZ3phYmNpbG54c3dicWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzYxMDYsImV4cCI6MjA2OTM1MjEwNn0.OkQE9Kg4_siIh5jX7aG2CIDwmYxP1Bm-8J8faQH6iHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});